# **numpy 공부**

##numpy 를 사용하는 이유

1. 리스트 보다 연산이 빠르다.
2. 대용량의 배열과 행렬 연산을 빠르게 수행할수있다.
3. 고차원적인 수학 연산자와 함수를 포함하고 있다.
4. 데이터 분석을 위한 패키지인 pands나 기계학습을 위한 
scikit-learn, tensorflow등이 넘파이 위에서 작동한다.

## numpy 연산

In [1]:
import numpy as np
import pandas as pd

a= np.array([1,2,3])
b = np.array([3,4,5])

In [2]:
a+b # 다른 연산들도 동일함

array([4, 6, 8])

In [3]:
num = np.array([100,200,300])
num += 10 # 모든 요소에 10씩 더함
num # 다은 연산들도 동일함

array([110, 210, 310])

## 다차원 배열

In [13]:
a = np.array([1,2,3]) # 1차원 배열
b = np.array([[1,2,3],[4,5,6]]) # 2차원 배열

a.shape # 객체의 형태 

(3,)

In [12]:
b.shape

(2, 3)

In [6]:
a.ndim # 객체의 차원

1

In [7]:
b.ndim

2

In [8]:
a.dtype # 객체 내부 자료형

dtype('int64')

In [9]:
a.itemsize # 객체 내부 자료형이 차지하는 메모리 크기(byte)

8

In [10]:
a.size # 객체의 전체 크기(항목의 수)

3

## 

## 인덱싱 슬라이싱

In [14]:
num1 = np.array([1, 2, 3, 4, 5 , 6 , 7 , 8 , 9])
num1[0] # 0번 자리수 출력

1

In [15]:
num1[:] #처음부터 끝까지 출력

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
num1[2:5] # 2번 자리에서부터 5번 자리 직전까지 출력

array([3, 4, 5])

In [17]:
num1[7:2:-1] # 7번 자리에서부터 2번자리 직전까지 거꾸로 출력

array([8, 7, 6, 5, 4])

In [19]:
num2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) # 2차원 배열
num2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
num2[1][2] # 2차원 배열에서 1행2열의 자리수 출력

6

### numpy 스타일의 인덱싱과 슬라이싱

In [23]:
num3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
num3[0,2]

3

In [24]:
num3[2,-1]

9

In [26]:
num3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

numpy는 리스트와 달리,numpy의 모든 항복은 동일한 자료형을 가진다.
int type의 num3에 float인 1.23을 삽입하면 강제 형변환 되어 1로 바뀐다.

In [28]:
num3[2,2] = 1.23
num3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

In [29]:
num3[0:2, 1:3] # 2차원 인덱싱

array([[2, 3],
       [5, 6]])

In [31]:
num3[0]

array([1, 2, 3])

In [32]:
num3[1, 1:3]

array([5, 6])

In [48]:
num3 = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16]])
num3 # 4행 4열

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
num3[::2][::2] # 논리적 오류, 값이 제대로 안나옴

array([[1, 2, 3, 4]])

In [50]:
num3[::2, ::2] # numpy식 슬라이싱을 적용했을 경우 오류 안나고 제대로 나옴

array([[ 1,  3],
       [ 9, 11]])

### 논리적인 인덱싱

In [51]:
age = np.array([18, 25, 19, 30, 28])
y = age >20 # age배열에서 20이상인 것들을 참 거짓으로 인덱싱한다.
y

array([False,  True, False,  True,  True])

In [53]:
age[ age > 20 ] # 부울형 배열을 인덱스로 하여 age에 보내면 20이상인것들만 출력된다.

array([25, 30, 28])

In [57]:
age = np.array([[1,2,3], [4,5,6], [7,8,9]]) #2차원 배열에서도 동일하게 적용됨
age

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
age > 5 

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [55]:
age[ age > 5 ] # 2차원 배열에서 5 이상인것들만 인덱스 형식으로 출력

array([6, 7, 8, 9])

In [56]:
age[ : , 2 ] # 마지막 3번쨰 열에서만 5보다 큰 값을 뽑아내고 싶을떄

array([3, 6, 9])

In [59]:
age[age % 2 == 0] #짝수만 뽑아내고싶을떄

array([2, 4, 6, 8])

## numpy의 다양한 함수