# Numpy 실습

이번 시간에는 Numpy 코드를 직접 작성해보고 응용하는 것을 목표한다.

In [4]:
int_data = [10,20,30,40,50]
float_data = [1.5, 2.5, 3.5, 4.5, 5.5]
str_data = ['박정현','김대로','새우깡','배고파','밥먹자']

In [5]:
import numpy as np

## 1. 주어진 list를 활용해 ndarray 만들기

- int_data
- float_data
- str_data
 
위 3가지 리스트를 이용하여 ndarray를 만들어 본다.

**요구사항 : array 제작 후 크기를 특정해보자.**

In [6]:
# here your code...
arr1 = np.array(int_data)
print(arr1, arr1.shape)

[10 20 30 40 50] (5,)


In [7]:
# here your code...
arr2 = np.array(float_data)
print(arr2, arr2.shape)

[1.5 2.5 3.5 4.5 5.5] (5,)


In [8]:
# here your code...
arr3 = np.array(str_data)
print(arr3, arr3.shape )

['박정현' '김대로' '새우깡' '배고파' '밥먹자'] (5,)


### 1-1. 직접 list를 통해 ndarray 만들기

자신이 원하는 list를 직접 array에 넣어 풀어보자.

**요구사항 : 1차원의 정수형, 2차원의 실수형, 3차원의 여러가지 자료형 각 1개 만들고 크기 구하기.**

In [9]:
# here your code...
arr1 = np.array([1,2,3,4,5])
print(arr1, arr1.shape)

[1 2 3 4 5] (5,)


In [10]:
# here your code...
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2, arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5)


In [40]:
# here your code...
arr3 = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,23,13,41,15],[33,44,55,66,77]]])

print(f"{arr3},{arr3.shape}")

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 23 13 41 15]
  [33 44 55 66 77]]],(1, 4, 5)


# 2. Numpy를 이용해 0과 1만 있는 array 만들기

이전 시간 우리는 모든 요소가 0인 array, 모든 요소가 1인 array를 제작해봤다.

이를 응용하여 0과 1인 array를 제작한다.

**요구사항 : 0인 요소 5개 1인 요소 5개의 2차원 array 만들기(행 수는 자유)** 

In [12]:
# here your code...
zeor1 = np.array([np.zeros(5),np.ones(5)])
print(f"{zeor1}")

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


## 2-1. random한 array를 만들어 사칙연산하기

1. random한 array를 만든다 (차원은 자유)
2. 사칙연산을 수행한다.

* 복습

- random.rand() : 이상한 소수 파파박
    - random.rand(3,5) : 크기가 3 * 5인 랜덤 array 리턴
    - random.rand(3,5,5) : 크기가 3 5 5인 랜덤 array 
- random.randn() : 0 ~ 1범위의 정규분포 리턴
    - random.randn(3,5) : 크기가 3 * 5인 랜덤 array 리턴
    - random.randn(3,5,5) : 크기가 3 5 5인 랜덤 array  
- random.randint() : 지정한 범위의 랜덤 정수 리턴
    - random.randint(0,10,10) : 0 ~ 10까지 10개 만들기 => 이때 같은 숫자 여러개 나올 수 있음
    - random.randint(low = 3) : 0 ~ 3까지 랜덤 정수 1개 리턴
    - random.randint(low =3, high = 5) : 3 ~ 5 까지 랜덤 정수 1개 리턴
    - random.randint(0,10,10) : 0 ~ 10까지 랜덤 정수 10개 리턴

In [41]:
# 정수형 랜덤 배열 만들기
# here your code...
arr1 = np.random.randint(0,3,5)
arr2 = np.random.rand(3,5)
print(f"{arr1},\n {arr2}")

[1 2 2 0 1],
 [[0.98867129 0.65043644 0.51042923 0.6585938  0.5127523 ]
 [0.43019695 0.86996839 0.31779532 0.84241633 0.1335709 ]
 [0.07470328 0.42667192 0.01785959 0.11285671 0.82841433]]


In [14]:
# here your code... +
arr3 = arr1 + arr2
arr3

array([[0.75057703, 1.57907307, 0.91557419, 0.38926684, 0.93183676],
       [0.1712721 , 0.86386094, 1.02095901, 0.40824078, 1.18447894],
       [1.07668995, 0.3905109 , 0.93149595, 1.29132766, 1.69398263]])

In [15]:
# here your code... -
arr3 = arr1 - arr2
arr3

array([[-0.66992825, -0.41577358, -0.09326892, -0.17843443, -0.02119138],
       [ 0.0510407 , -0.14123845, -0.68223664,  0.39535985, -0.05442918],
       [-0.43080557, -0.09108898, -0.05232391,  0.11000367,  0.25264567]])

In [16]:
# here your code... *
arr3 = arr1 * arr2
arr3

array([[0.02864051, 0.58015103, 0.20739425, 0.02992246, 0.21696767],
       [0.00668224, 0.18157686, 0.14422762, 0.00258778, 0.35000696],
       [0.24341695, 0.03605039, 0.21623673, 0.41385658, 0.70143683]])

In [17]:
# here your code... /
arr3 = arr1 / arr2
arr3

array([[5.67747147e-02, 5.83152338e-01, 8.15097282e-01, 3.71379146e-01,
        9.55528316e-01],
       [1.84904117e+00, 7.18956251e-01, 1.98874611e-01, 6.23868199e+01,
        9.12133623e-01],
       [4.28448620e-01, 6.21723423e-01, 8.93631122e-01, 1.18623793e+00,
        1.35057127e+00]])

## 2-2. 브로드 캐스트 실습하기

**array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만,**

numpy에서는 브로드캐스트라는 기능을 제공한다.

브로드캐스트란, **서로 크기가 다른 array가 연산이 가능하게끔 하는 것이다.**

1차원 array * 2차원 array 해보기

In [18]:
# here your code...
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[6,7,8,9,10],[11,12,13,14,15]])
arr1 + arr2

array([[ 7,  9, 11, 13, 15],
       [12, 14, 16, 18, 20]])

## 2-3. array와 스칼라 연산

array에 어떤수를 곱해 0을 만들어 보자!

In [19]:
# here your code...
arr1*0

array([0, 0, 0, 0, 0])

# 3. Array 인덱싱
numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.

**이때, python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작하는 것에 주의한다.**

## 3-1. array를 만들어 N번째 요소 가져오기

0 ~ 10까지의 array를 만들어 주어진 번호에 맞는 요소를 구해보자

요구사항 : N = 3 , M = 7이며, 구하고자 하는 값은 3번째 요소, 7번째 요소, 3부터7까지의 모든 요소 이다.

In [20]:
N, M = 3, 7
# here your code...
arr1 = np.array([0,1,2,3,4,5,6,7,8,9,10])

print(f"{arr1[3]},\n,{arr1[7]},\n,{arr1[3:7]} ")


3,
,7,
,[3 4 5 6] 


## 3-2. 2차원 array를 만들어 요소 가져오기

1. N행의 모든 요소 가져오기
2. M열의 모든 요소 가져오기
3. N행의 M열 요소 가져오기

In [21]:
# here your code..
arr4 = np.random.rand(3,7)


print(f"{arr4},\n\n,{arr4[2:3,:]},\n\n,{arr4[:,6:7]},\n\n,{arr4[2:3,6:7]}")

[[0.32908062 0.62563772 0.68023749 0.38928742 0.45606026 0.56581843
  0.06612532]
 [0.7796618  0.6279397  0.68455675 0.22772851 0.70735853 0.69919068
  0.02684735]
 [0.7967406  0.40753258 0.88229176 0.18147203 0.08870659 0.94710623
  0.85545976]],

,[[0.7967406  0.40753258 0.88229176 0.18147203 0.08870659 0.94710623
  0.85545976]],

,[[0.06612532]
 [0.02684735]
 [0.85545976]],

,[[0.85545976]]


# 4. Array boolean 인덱싱 (aka. 마스크)

위에서 이용한 다차원의 인덱싱을 응용하여 boolean 인덱싱을 할 수 있다.

해당 기능은 주로 마스크라고 이야기하는데, boolean인덱싱을 통해 만들어낸 array를 통해

우리가 원하는 행 또는 열의 값만 뽑아낼 수 있다.

**즉, 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.**

원하는 문자열 형태의 array를 만들고 이를 활용해 인덱싱 해보자

In [22]:
rand_arr = np.random.randn(9,4)
names = np.array(['박정현','김대로','공지환','이수원','이지민','박민서','정지우','나지성','정소영'])
rand_arr

array([[-1.88920259, -0.45643068, -0.42086786,  0.05576428],
       [ 0.23810206,  0.61114621, -0.93980852,  0.98039688],
       [ 0.20007769, -0.8953573 ,  0.26766831,  0.28409541],
       [ 1.00562049,  1.14254005,  0.18150722, -1.56282111],
       [ 1.24842396,  0.07658794,  0.69214907,  0.19067282],
       [-0.19277595,  2.08016494,  0.03597558, -0.45970957],
       [ 0.74030835, -1.55704753, -1.72730586,  1.38851169],
       [ 0.11832892, -0.20559736,  0.60848205,  2.38667078],
       [ 0.10297978,  0.28971086,  1.43113696, -0.24202707]])

In [42]:
# here your code...
str_arr = np.array(["1","1","2","3"])

mask = (str_arr == "1")
mask

rand_arr[:,mask]

array([[-1.88920259, -0.45643068],
       [ 0.23810206,  0.61114621],
       [ 0.20007769, -0.8953573 ],
       [ 1.00562049,  1.14254005],
       [ 1.24842396,  0.07658794],
       [-0.19277595,  2.08016494],
       [ 0.74030835, -1.55704753],
       [ 0.11832892, -0.20559736],
       [ 0.10297978,  0.28971086]])

## 4-1. 논리 연산자를 이용해서 인덱싱 하기

논리 연산자 : Python에서는 &, |(shift + \키) 등이 있다. 이를 활용하자

In [24]:
# here your code...
rand_arr[(names == '정지우') | (names == '정소영'), :]

array([[ 0.74030835, -1.55704753, -1.72730586,  1.38851169],
       [ 0.10297978,  0.28971086,  1.43113696, -0.24202707]])

# 5. 통계 함수를 사용해 array의 값의 통계 구하기

- sum()
- max()
- min()
- mean()
- std()

In [25]:
arr1 = np.array([[-0.30008319,  0.65933097, -1.09470069],
       [-0.76411229,  1.02447394, -0.14375934],
       [ 1.5411538 , -0.56123682, -1.35981521],
       [ 1.9785256 ,  1.62245077,  0.52825544],
       [-1.45083326, -0.41862805,  0.71180435]])

In [26]:
# here your code...
np.sum(arr1)

1.97282602

In [27]:
# here your code...
np.max(arr1)

1.9785256

In [28]:
# here your code...
np.min(arr1)

-1.45083326

In [29]:
# here your code...
np.mean(arr1)

0.13152173466666667

In [30]:
# here your code...
np.std(arr1)

1.0729952978262813

## 5-1. 전체 성분의 최소값, 최대값이 위치한 인덱스 반환하기

- argmin() : 최소값이 있는 인덱스 반환
- argmax() : 최대값이 있는 인덱스 반환 

In [31]:
# here your code...
np.argmin(arr1)

12

In [32]:
np.argmax(arr1)

9

## 5-2. 처음부터 각 성분의 누적합, 누적곱 계산

- cumsum() : 누적 합
- cumprod() : 누적 곱

In [33]:
# here your code...
np.cumsum(arr1)

array([-0.30008319,  0.35924778, -0.73545291, -1.4995652 , -0.47509126,
       -0.6188506 ,  0.9223032 ,  0.36106638, -0.99874883,  0.97977677,
        2.60222754,  3.13048298,  1.67964972,  1.26102167,  1.97282602])

In [34]:
np.cumprod(arr1)

array([-0.30008319, -0.19785414,  0.21659106, -0.16549989, -0.16955033,
        0.02437444,  0.03756477, -0.02108273,  0.02866862,  0.05672159,
        0.09202799,  0.04861429, -0.07053122,  0.02952635,  0.02101698])

# 6. array 정렬 하기

오름차순, 내림차순 정렬을 해보자

In [35]:
# 오름차순
# here your code..
np.sort(arr1)

array([[-1.09470069, -0.30008319,  0.65933097],
       [-0.76411229, -0.14375934,  1.02447394],
       [-1.35981521, -0.56123682,  1.5411538 ],
       [ 0.52825544,  1.62245077,  1.9785256 ],
       [-1.45083326, -0.41862805,  0.71180435]])

In [36]:
# 내림차순
# here your code..
np.sort(arr1)[::-1]

array([[-1.45083326, -0.41862805,  0.71180435],
       [ 0.52825544,  1.62245077,  1.9785256 ],
       [-1.35981521, -0.56123682,  1.5411538 ],
       [-0.76411229, -0.14375934,  1.02447394],
       [-1.09470069, -0.30008319,  0.65933097]])

# 고생했어요^^

다음 시간에는 **pandas**에 대해서 알아보도록 하겠습니다.

질문이나 문의사항은 **github issues**를 활용해주세요(방법 모르면 개인적으로 물어봐주길)

기타 모두가 보면 안될 질문은 갠톡 부탁합니다.^^