# Numpy 실습

이번 시간에는 Numpy 코드를 직접 작성해보고 응용하는 것을 목표한다.

In [44]:
int_data = [10,20,30,40,50]
float_data = [1.5, 2.5, 3.5, 4.5, 5.5]
str_data = ['박정현','김대로','새우깡','배고파','밥먹자']

In [45]:
import numpy as np 
# 넘파이 라이브러리 사용을 위해서 아나콘다에서 numpy를 가져온다.
# as의 의미는 numpy를 np라고 줄여서 사용하겠다 의미

## 1. 주어진 list를 활용해 ndarray 만들기

- int_data
- float_data
- str_data
 
위 3가지 리스트를 이용하여 ndarray를 만들어 본다.

**요구사항 : array 제작 후 크기를 특정해보자.**

In [46]:
arr1 = np.array(int_data)
# 넘파이 배열을 생성하기 위해 array() 함수를 사용한다. 이때 array(리스트 또는 [....]) 형식으로 넣어주면 된다.
print(f"배열 : {arr1} 크기 : {arr1.shape}")
# 변수.shape = 해당 배열의 크기를 알려준다.

배열 : [10 20 30 40 50] 크기 : (5,)


In [47]:
arr2 = np.array(float_data)
print(f"배열 : {arr2} 크기 : {arr2.shape}")

배열 : [1.5 2.5 3.5 4.5 5.5] 크기 : (5,)


In [48]:
arr3 = np.array(str_data)
print(f"배열 : {arr3} 크기 : {arr3.shape}")

배열 : ['박정현' '김대로' '새우깡' '배고파' '밥먹자'] 크기 : (5,)


### 1-1. 직접 list를 통해 ndarray 만들기

자신이 원하는 list를 직접 array에 넣어 풀어보자.

**요구사항 : 1차원의 정수형, 2차원의 실수형, 3차원의 여러가지 자료형 각 1개 만들고 크기 구하기.**

In [49]:
arr4 = np.array([1,2,3,4,5,6,7,8,9,10]) # 1차원의 정수형 
# 이전 문제에서는 array(변수명)으로 배열을 생성했다면 이번에는 array([...])형식으로 배열을 생성함
# [...]는 파이썬의 기본 자료형인 리스트이다.
print(f"배열 : {arr4} 크기 : {arr4.shape}")

배열 : [ 1  2  3  4  5  6  7  8  9 10] 크기 : (10,)


In [50]:
arr5 = np.array([[0.1,1.2,1.3,1.4,1.5,1.6], # 2차원의 실수형
                [5.6,1.2,1.5,0.4,0.1,4.5],
                [.04,.5,.6,.7,.8,.9]]) # 0.5을 표현할 경우 0을 생략해도 정상적으로 인식함 ex) .6 == 0.6
print(f"배열 : {arr5} \n크기 : {arr5.shape}")

배열 : [[0.1  1.2  1.3  1.4  1.5  1.6 ]
 [5.6  1.2  1.5  0.4  0.1  4.5 ]
 [0.04 0.5  0.6  0.7  0.8  0.9 ]] 
크기 : (3, 6)


In [51]:
arr6 = np.array([[["가","나","다","라","마","바"],
                ["a","b","c","d","e","f"],
                ["1","2","3","4","5","6"]]])

print(f"배열 : {arr6} \n크기 : {arr6.shape}")

배열 : [[['가' '나' '다' '라' '마' '바']
  ['a' 'b' 'c' 'd' 'e' 'f']
  ['1' '2' '3' '4' '5' '6']]] 
크기 : (1, 3, 6)


# 2. Numpy를 이용해 0과 1만 있는 array 만들기

이전 시간 우리는 모든 요소가 0인 array, 모든 요소가 1인 array를 제작해봤다.

이를 응용하여 0과 1인 array를 제작한다.

**요구사항 : 0인 요소 5개 1인 요소 5개의 2차원 array 만들기(행 수는 자유)** 

In [52]:
arr_zero = np.zeros((5, 5)) # np.zeros() 괄호안에 들어가는 만들고 싶은 배열의 크기 1차원이면 숫자 1개 2차원 이상부터는 (행, 열) 이렇게 넣어줘야함
arr_one = np.ones((5, 5))
print(f"zero : {arr_zero} \n\n one : {arr_one}\n\n\n")

zero : [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

 one : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]





# Tip


np.append() vs np.concatenate() 차이

**둘다 병합인데 무슨 차이인가?**

append는 주로 1차원을 병합할때 사용함 왜냐하면 무조건 결과를 1차원으로 나태나기 때문임

concatenate()는 다차원 배열(2차원 이상) 병합시 사용함 왜냐하면 열, 행의 옵션(axis)을 통해 다차원 병합이 가능

In [53]:
# 합치는 방법
arr_col = np.concatenate((arr_zero,arr_one), axis = 1)
arr_raw = np.concatenate((arr_zero, arr_one), axis = 0)

print(f"열기준 : {arr_col}\n\n행기준 : {arr_raw}")

열기준 : [[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]]

행기준 : [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
# append를 이용한 방법도 있지만 이건 무조건 1차원으로 나타냄
print(np.append(arr_zero,arr_one))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


## 2-1. random한 array를 만들어 사칙연산하기

1. random한 array를 만든다 (차원은 자유)
2. 사칙연산을 수행한다.

* 복습

- random.rand() : 이상한 소수 파파박
    - random.rand(3,5) : 크기가 3 * 5인 랜덤 array 리턴
    - random.rand(3,5,5) : 크기가 3 5 5인 랜덤 array 
- random.randn() : 0 ~ 1범위의 정규분포 리턴
    - random.randn(3,5) : 크기가 3 * 5인 랜덤 array 리턴
    - random.randn(3,5,5) : 크기가 3 5 5인 랜덤 array  
- random.randint() : 지정한 범위의 랜덤 정수 리턴
    - random.randint(0,10,10) : 0 ~ 10까지 10개 만들기 => 이때 같은 숫자 여러개 나올 수 있음
    - random.randint(low = 3) : 0 ~ 3까지 랜덤 정수 1개 리턴
    - random.randint(low =3, high = 5) : 3 ~ 5 까지 랜덤 정수 1개 리턴
    - random.randint(0,10,10) : 0 ~ 10까지 랜덤 정수 10개 리턴

In [55]:
# 정수형 랜덤 배열 만들기
arr_rand1 = np.random.randint(0,10,10)
arr_rand2 = np.random.randint(0,10,10)
print(f"{arr_rand1}  {arr_rand2}")

[1 6 3 2 7 2 7 6 7 0]  [9 9 3 9 9 2 6 9 2 3]


In [83]:
arr_add = np.add(arr_rand1,arr_rand2)
print(f"브로드캐스트 방법 : {arr_rand1 + arr_rand2}\n\nadd 함수 적용 : {arr_add}")

브로드캐스트 방법 : [10 15  6 11 16  4 13 15  9  3]

add 함수 적용 : [10 15  6 11 16  4 13 15  9  3]


In [84]:
arr_sub = np.subtract(arr_rand1, arr_rand2)
print(f"브로드캐스트 방법 : {arr_rand1 - arr_rand2}\n\nsubtract 함수 적용 : {arr_sub}")

브로드캐스트 방법 : [-8 -3  0 -7 -2  0  1 -3  5 -3]

subtract 함수 적용 : [-8 -3  0 -7 -2  0  1 -3  5 -3]


In [85]:
arr_mul = np.multiply(arr_rand1, arr_rand2)
print(f"브로드캐스트 방법 : {arr_rand1 * arr_rand2}\n\nmultiply 함수 적용 : {arr_mul}")

브로드캐스트 방법 : [ 9 54  9 18 63  4 42 54 14  0]

multiply 함수 적용 : [ 9 54  9 18 63  4 42 54 14  0]


In [133]:
arr_div = np.divide(arr_rand1, arr_rand2)
print(f"브로드캐스트 방법:{arr_rand1 / arr_rand2}\n\ndivide 함수 적용:{arr_div}")

브로드캐스트 방법:[0.11111111 0.66666667 1.         0.22222222 0.77777778 1.
 1.16666667 0.66666667 3.5        0.        ]

divide 함수 적용:[0.11111111 0.66666667 1.         0.22222222 0.77777778 1.
 1.16666667 0.66666667 3.5        0.        ]


## 2-2. 브로드 캐스트 실습하기

**array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만,**

numpy에서는 브로드캐스트라는 기능을 제공한다.

브로드캐스트란, **서로 크기가 다른 array가 연산이 가능하게끔 하는 것이다.**

1차원 array * 2차원 array 해보기

In [96]:
# here your code...
arr_one_dim = np.random.rand(5) # 5개의 요소를 가진 배열 생성
arr_two_dim = np.random.rand(3,5) # 3행 5열의 배열 생성
arr_one_dim * arr_two_dim

# 무 조 건 1차원의 요소 갯수 = 2차원 열의 수

array([[0.14729065, 0.05737302, 0.56077996, 0.35579158, 0.28302465],
       [0.17962055, 0.01706015, 0.39350534, 0.03825654, 0.11168766],
       [0.03734814, 0.13436525, 0.16252038, 0.09340158, 0.59316071]])

## 2-3. array와 스칼라 연산

array에 어떤수를 곱해 0을 만들어 보자!

In [99]:
arr_x = np.random.rand(5,6)
arr_x * 0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 3. Array 인덱싱
numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.

**이때, python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작하는 것에 주의한다.**

## 3-1. array를 만들어 N번째 요소 가져오기

0 ~ 10까지의 array를 만들어 주어진 번호에 맞는 요소를 구해보자

요구사항 : N = 3 , M = 7이며, 구하고자 하는 값은 3번째 요소, 7번째 요소, 3부터7까지의 모든 요소 이다.

In [102]:
N, M = 3, 7
arr_indexing = np.random.randint(0,20,20)
print(f"배열 : {arr_indexing}\n\n인덱싱 후 : {arr_indexing[N:M]}")

배열 : [ 5  8  5 10 19 13 19  9 16  6 18  3  2  6 10  2 18 18 10  8]

인덱싱 후 : [10 19 13 19]


In [105]:
for i,v in enumerate(arr_indexing):
    print(f"인덱스 번호 : {i} 요소 값 : {v}")

인덱스 번호 : 0 요소 값 : 5
인덱스 번호 : 1 요소 값 : 8
인덱스 번호 : 2 요소 값 : 5
인덱스 번호 : 3 요소 값 : 10
인덱스 번호 : 4 요소 값 : 19
인덱스 번호 : 5 요소 값 : 13
인덱스 번호 : 6 요소 값 : 19
인덱스 번호 : 7 요소 값 : 9
인덱스 번호 : 8 요소 값 : 16
인덱스 번호 : 9 요소 값 : 6
인덱스 번호 : 10 요소 값 : 18
인덱스 번호 : 11 요소 값 : 3
인덱스 번호 : 12 요소 값 : 2
인덱스 번호 : 13 요소 값 : 6
인덱스 번호 : 14 요소 값 : 10
인덱스 번호 : 15 요소 값 : 2
인덱스 번호 : 16 요소 값 : 18
인덱스 번호 : 17 요소 값 : 18
인덱스 번호 : 18 요소 값 : 10
인덱스 번호 : 19 요소 값 : 8


## 3-2. 2차원 array를 만들어 요소 가져오기

1. N행의 모든 요소 가져오기
2. M열의 모든 요소 가져오기
3. N행의 M열 요소 가져오기

In [114]:
# 현재 N = 3 , M = 7 
arr_two_dim_indexing = np.random.randint(10, size=(4,8))
print(f"배열 : \n{arr_two_dim_indexing}")
print(f"3행의 모든 요소 가져오기 : {arr_two_dim_indexing[N,:]}")
print(f"7열의 모든 요소 가져오기 : {arr_two_dim_indexing[:,M]}")
print(f"3행 7열의 요소 가져오기 : {arr_two_dim_indexing[N,M]}")

배열 : 
[[3 8 8 6 6 6 3 8]
 [8 3 4 2 6 0 5 4]
 [3 3 3 7 2 3 0 5]
 [8 9 5 9 5 4 7 6]]
3행의 모든 요소 가져오기 : [8 9 5 9 5 4 7 6]
7열의 모든 요소 가져오기 : [8 4 5 6]
3행 7열의 요소 가져오기 : 6


# 4. Array boolean 인덱싱 (aka. 마스크)

위에서 이용한 다차원의 인덱싱을 응용하여 boolean 인덱싱을 할 수 있다.

해당 기능은 주로 마스크라고 이야기하는데, boolean인덱싱을 통해 만들어낸 array를 통해

우리가 원하는 행 또는 열의 값만 뽑아낼 수 있다.

**즉, 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.**

원하는 문자열 형태의 array를 만들고 이를 활용해 인덱싱 해보자

In [65]:
rand_arr = np.random.randn(9,4)
rand_arr

array([[-2.65379829, -0.39229186, -0.60187498,  0.66336337],
       [-0.3197116 ,  0.01500733, -0.7054033 , -0.64026212],
       [-0.19833073,  1.25637368, -0.48885718, -1.11642334],
       [-0.78034953, -0.28984636,  0.38642811, -0.54728812],
       [-0.67852066, -0.36907065,  1.27701136,  1.87702117],
       [ 0.15510605, -0.35189849, -0.19651811, -0.99956056],
       [-0.08696091, -2.25296817, -0.15048171,  2.10799978],
       [-0.01906754, -0.08904206, -1.12901716, -0.76880264],
       [-0.33501377, -0.05361371, -0.39661403,  0.34857904]])

In [66]:
# here your code...
str_arr = np.array(["1","1","2","3"])

mask = (str_arr == "1")
mask

rand_arr[:,mask]

array([[-2.65379829, -0.39229186],
       [-0.3197116 ,  0.01500733],
       [-0.19833073,  1.25637368],
       [-0.78034953, -0.28984636],
       [-0.67852066, -0.36907065],
       [ 0.15510605, -0.35189849],
       [-0.08696091, -2.25296817],
       [-0.01906754, -0.08904206],
       [-0.33501377, -0.05361371]])

## 4-1. 논리 연산자를 이용해서 인덱싱 하기

논리 연산자 : Python에서는 &, |(shift + \키) 등이 있다. 이를 활용하자

In [67]:
# here your code...
rand_arr[:,(str_arr == "1" )|(str_arr == "2")]

array([[-2.65379829, -0.39229186, -0.60187498],
       [-0.3197116 ,  0.01500733, -0.7054033 ],
       [-0.19833073,  1.25637368, -0.48885718],
       [-0.78034953, -0.28984636,  0.38642811],
       [-0.67852066, -0.36907065,  1.27701136],
       [ 0.15510605, -0.35189849, -0.19651811],
       [-0.08696091, -2.25296817, -0.15048171],
       [-0.01906754, -0.08904206, -1.12901716],
       [-0.33501377, -0.05361371, -0.39661403]])

# 5. 통계 함수를 사용해 array의 값의 통계 구하기

- sum()
- max()
- min()
- mean()
- std()

In [124]:
arr_statistics = np.around(np.random.rand(10,8),2) # around()는 넘파이에서 지원하는 자릿수 반올림 함수임
print(
    f"sum : {arr_statistics.sum()}\
    \nmax : {arr_statistics.max()}\
    \nmin : {arr_statistics.min()}\
    \nmean : {arr_statistics.mean()}\
    \nstd: {arr_statistics.std()}"
    )

sum : 42.78    
max : 1.0    
min : 0.02    
mean : 0.5347500000000001    
std: 0.278953289100523


## 5-1. 전체 성분의 최소값, 최대값이 위치한 인덱스 반환하기

- argmin() : 최소값이 있는 인덱스 반환
- argmax() : 최대값이 있는 인덱스 반환 

In [126]:
print(
    f"최대값 인덱스 : {arr_statistics.argmax()}\
    \n최소값 인덱스 : {arr_statistics.argmin()}"
    )

최대값 인덱스 : 73    
최소값 인덱스 : 3


## 5-2. 처음부터 각 성분의 누적합, 누적곱 계산

- cumsum() : 누적 합
- cumprod() : 누적 곱

In [75]:
# here your code...
arr1.cumsum()

array([-0.30008319,  0.35924778, -0.73545291, -1.4995652 , -0.47509126,
       -0.6188506 ,  0.9223032 ,  0.36106638, -0.99874883,  0.97977677,
        2.60222754,  3.13048298,  1.67964972,  1.26102167,  1.97282602])

In [76]:
arr2.cumprod()

array([          2,           6,          24,         120,         720,
              1440,        2880,        5760,       11520,       23040,
             46080,      138240,      552960,     2764800,    16588800,
          33177600,    66355200,   132710400,   265420800,   530841600,
        1061683200, -1109917696,  -144703488,  -723517440,   -46137344,
         -92274688,  -184549376,  -369098752,  -738197504, -1476395008],
      dtype=int32)

# 6. array 정렬 하기

오름차순, 내림차순 정렬을 해보자

In [130]:
arr_sort = np.random.randint(15, size= (5,5))
print(f"정렬 전 : \n{arr_sort}\n정렬 후 : \n{np.sort(arr_sort)}")

정렬 전 : 
[[13  5  8 10  3]
 [ 4  4  2 13  0]
 [ 1  5  8 11 12]
 [ 1 13  0  2  3]
 [ 5  2 12 14  2]]
정렬 후 : 
[[ 3  5  8 10 13]
 [ 0  2  4  4 13]
 [ 1  5  8 11 12]
 [ 0  1  2  3 13]
 [ 2  2  5 12 14]]


In [131]:
arr_sort = np.random.randint(15, size= (5,5))
print(f"정렬 전 : \n{arr_sort}\n정렬 후 : \n{np.sort(arr_sort)[::-1]}")

정렬 전 : 
[[13  4  1  5 14]
 [13 13  3  2  1]
 [ 2 14  8  1  9]
 [ 9  0  8  0 11]
 [ 2 13  0 11 12]]
정렬 후 : 
[[ 0  2 11 12 13]
 [ 0  0  8  9 11]
 [ 1  2  8  9 14]
 [ 1  2  3 13 13]
 [ 1  4  5 13 14]]


# 고생했어요^^

다음 시간에는 **pandas**에 대해서 알아보도록 하겠습니다.

질문이나 문의사항은 **github issues**를 활용해주세요(방법 모르면 개인적으로 물어봐주길)

기타 모두가 보면 안될 질문은 갠톡 부탁합니다.^^